### ISSUE TITLE
Issue in displaying the tickets assigned to an agent.

### ISSUE THREAD

**Issue by SaranyaSwaminathan** [frappe/helpdesk#2000]
### Information about bug

When an Agent is selected, ideally only the tickets assigned to that particular agent should be displayed. 
But currently all the tickets are getting displayed.

### Version

Frappe Version - 15.41.0
Helpdesk Version - 0.10.0

### Installation method

manual install

**Comment by RitvikSardana** [comment]
Can you explain more on the issue?
This should work now

**Comment by nikitadattapawar06** [comment]
This Issue still exists 
The issue is if i navigate to helpdesk HD Ticket i can see all the HD Ticket created in the system but the working should be as an agent i should  only be able to view the tickets that are assigned to me rather then all the tickets in system.
